// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZambaFarm.Models;

#nullable disable

namespace ZambaFarm.Migrations
{
    [DbContext(typeof(FarmContext))]
    partial class FarmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ZambaFarm.Models.Cattle", b =>
                {
                    b.Property<int>("CattleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CattleId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsMating")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNursing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MatingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MotherCattleId")
                        .HasColumnType("int");

                    b.Property<string>("MotherTagNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MotherTagNumber");

                    b.Property<int?>("NumberOfBabiesNursed")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfCalves")
                        .HasColumnType("int");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CattleId");

                    b.HasIndex("MotherCattleId");

                    b.ToTable("Cattles");
                });

            modelBuilder.Entity("ZambaFarm.Models.Chicken", b =>
                {
                    b.Property<int>("ChickenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChickenId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsEggLaying")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMated")
                        .HasColumnType("bit");

                    b.Property<int?>("IsNursing")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MatingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MotherChickenId")
                        .HasColumnType("int");

                    b.Property<string>("MotherTagNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfEggs")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfEggsLaid")
                        .HasColumnType("int");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChickenId");

                    b.HasIndex("MotherChickenId");

                    b.ToTable("Chicken");
                });

            modelBuilder.Entity("ZambaFarm.Models.Duck", b =>
                {
                    b.Property<int>("DuckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DuckId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsEggLaying")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MatingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MotherDuckId")
                        .HasColumnType("int");

                    b.Property<string>("MotherTagNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfEggs")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfEggsLaid")
                        .HasColumnType("int");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DuckId");

                    b.HasIndex("MotherDuckId");

                    b.ToTable("Duck");
                });

            modelBuilder.Entity("ZambaFarm.Models.Goat", b =>
                {
                    b.Property<int>("GoatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoatId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsMating")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNursing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MatingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MotherGoatId")
                        .HasColumnType("int");

                    b.Property<string>("MotherTagNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MotherTagNumber");

                    b.Property<int?>("NumberOfBabiesNursed")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfKids")
                        .HasColumnType("int");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GoatId");

                    b.HasIndex("MotherGoatId");

                    b.ToTable("Goats");
                });

            modelBuilder.Entity("ZambaFarm.Models.Pig", b =>
                {
                    b.Property<int>("PigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PigId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsMating")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNursing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MatingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MotherPigId")
                        .HasColumnType("int");

                    b.Property<string>("MotherTagNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MotherTagNumber");

                    b.Property<int?>("NumberOfBabiesNursed")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfPiglets")
                        .HasColumnType("int");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PigId");

                    b.HasIndex("MotherPigId");

                    b.ToTable("Pigs");
                });

            modelBuilder.Entity("ZambaFarm.Models.Rabbit", b =>
                {
                    b.Property<int>("RabbitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RabbitId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Cage")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsMating")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNursing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MatingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MotherRabbitId")
                        .HasColumnType("int");

                    b.Property<string>("MotherTagNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MotherTagNumber");

                    b.Property<int?>("NumberOfBabiesNursed")
                        .HasColumnType("int");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RabbitId");

                    b.HasIndex("MotherRabbitId");

                    b.ToTable("Rabbits");
                });

            modelBuilder.Entity("ZambaFarm.Models.Turkey", b =>
                {
                    b.Property<int>("TurkeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurkeyId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsEggLaying")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MatingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotherTagNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MotherTagNumber");

                    b.Property<int?>("MotherTurkeyId")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfEggs")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfEggsLaid")
                        .HasColumnType("int");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TurkeyId");

                    b.HasIndex("MotherTurkeyId");

                    b.ToTable("turkeys", (string)null);
                });

            modelBuilder.Entity("ZambaFarm.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZambaFarm.Models.Cattle", b =>
                {
                    b.HasOne("ZambaFarm.Models.Cattle", "Mother")
                        .WithMany("Offspring")
                        .HasForeignKey("MotherCattleId");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("ZambaFarm.Models.Chicken", b =>
                {
                    b.HasOne("ZambaFarm.Models.Chicken", "Mother")
                        .WithMany("Offspring")
                        .HasForeignKey("MotherChickenId");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("ZambaFarm.Models.Duck", b =>
                {
                    b.HasOne("ZambaFarm.Models.Duck", "Mother")
                        .WithMany("Offspring")
                        .HasForeignKey("MotherDuckId");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("ZambaFarm.Models.Goat", b =>
                {
                    b.HasOne("ZambaFarm.Models.Goat", "Mother")
                        .WithMany("Offspring")
                        .HasForeignKey("MotherGoatId");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("ZambaFarm.Models.Pig", b =>
                {
                    b.HasOne("ZambaFarm.Models.Pig", "Mother")
                        .WithMany("Offspring")
                        .HasForeignKey("MotherPigId");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("ZambaFarm.Models.Rabbit", b =>
                {
                    b.HasOne("ZambaFarm.Models.Rabbit", "Mother")
                        .WithMany("Offspring")
                        .HasForeignKey("MotherRabbitId");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("ZambaFarm.Models.Turkey", b =>
                {
                    b.HasOne("ZambaFarm.Models.Turkey", "Mother")
                        .WithMany("Offspring")
                        .HasForeignKey("MotherTurkeyId");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("ZambaFarm.Models.Cattle", b =>
                {
                    b.Navigation("Offspring");
                });

            modelBuilder.Entity("ZambaFarm.Models.Chicken", b =>
                {
                    b.Navigation("Offspring");
                });

            modelBuilder.Entity("ZambaFarm.Models.Duck", b =>
                {
                    b.Navigation("Offspring");
                });

            modelBuilder.Entity("ZambaFarm.Models.Goat", b =>
                {
                    b.Navigation("Offspring");
                });

            modelBuilder.Entity("ZambaFarm.Models.Pig", b =>
                {
                    b.Navigation("Offspring");
                });

            modelBuilder.Entity("ZambaFarm.Models.Rabbit", b =>
                {
                    b.Navigation("Offspring");
                });

            modelBuilder.Entity("ZambaFarm.Models.Turkey", b =>
                {
                    b.Navigation("Offspring");
                });
#pragma warning restore 612, 618
        }
    }
}
